# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ff6b61f0cf2e3efd65a06c9e97630e7071fa21f5b225cc893822f81066a6b0f64cd87d6433551479aed5eb30c8ae9e1de07eb3568c3549f3bf133d451755a3ab

test:
  secret_key_base: 6ec0918f4e29ee45b2e50c7a92ee8b4e6821e7d094d2c70b0c6324e46e6bcb1724cb8346b6b73141b729aeb712912d816d8618aca2afb928769a9116dc3dc8ca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
